#pragma once

#define IDI_MAIN_APP 1

#define IDR_IMS_DOCUMENT_ICO 201
#define IDR_EASTEREGG_ICO 202
#define IDR_EXPLORER_GUI_ICO 203
#define IDR_PACKER_GUI_ICO 204
#define IDR_PLAYER_GUI_ICO 205
#define IDR_SETMIDI_ICO 206
#define IDR_SYSEX_GENERATOR_GUI_ICO 207
#define IDR_PACKER_COMMANDLINE_ICO 208
#define IDR_PROBE_COMMANDLINE_ICO 209
